<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mandeeps-MacBook-Air.local" failures="0" tests="3" name="UMA test" time="0.402" errors="0" timestamp="2 Jul 2018 08:20:17 GMT">
  <testcase classname="testCases.UMA_ChanLine_CRM" name="@BeforeTest st" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at com.relevantcodes.extentreports.Report.setFilePath(Report.java:527)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:80)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:375)
	at reports.GenExtentReports.startTest(GenExtentReports.java:21)
	at testCases.UMA_ChanLine_CRM.st(UMA_ChanLine_CRM.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest st -->
  <testcase classname="testCases.UMA_ChanLine_TVAM" name="@AfterTest Down" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest Down -->
  <testcase classname="testCases.UMA_ChanLine_CRM" name="UMA_ChanLine_CRM_test" time="0.002">
    <skipped/>
  </testcase> <!-- UMA_ChanLine_CRM_test -->
  <testcase classname="testCases.UMA_ChanLine_OMS" name="UMA_ChanLine_OMS_test" time="0.002">
    <skipped/>
  </testcase> <!-- UMA_ChanLine_OMS_test -->
  <testcase classname="testCases.UMA_ChanLine_TVAM" name="UMA_ChanLine_CRM_test" time="0.002">
    <skipped/>
  </testcase> <!-- UMA_ChanLine_CRM_test -->
</testsuite> <!-- UMA test -->
